### ISSUE TITLE
什么时候支持ROS2？

### ISSUE THREAD

**Issue by quandy2020** [AndrewZheng-1011/legged_planner#1]
什么时候支持ROS2？

**Comment by AndrewZheng-1011** [comment]
Hey,

I can only speak English so I hope this answers the question. Currently, there is no work to support for ROS2 as we have not had the need to. Perhaps in the future, we will work on that, but not anytime soon. Of course, I would be happy if someone create a ROS2 support version, but I can only offer minimal support.

Here is a google translate of what I stated:

嘿，

我只会说英语，所以希望这回答了你的问题。目前，并没有计划支持ROS2，因为我们还没有需要。也许在将来，我们会着手处理这个问题，但不会很快。当然，如果有人创建了ROS2支持版本，我会很高兴，但我只能提供有限的支持。
